# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: migrations
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    # active: ${SPRING_PROFILES_ACTIVE} #spring.profiles.active#
    active: ${SPRING_PROFILES_ACTIVE} #spring.profiles.active#
  jmx:
    enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jackson:
    serialization:
      write-durations-as-timestamps: false
  jpa:
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.hbm2ddl.auto: validate
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: false
      hibernate.generate_statistics: false
      hibernate.batch_versioned_data: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  task:
    execution:
      thread-name-prefix: app-executor-
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: app-scheduling-
      pool:
        size: 10
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.xml
  main:
    allow-bean-definition-overriding: false
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760
      file-size-threshold: 0
      location: /tmp

server:
  servlet:
    session:
      cookie:
        http-only: true
  tomcat:
    max-http-form-post-size: 10485760
