# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    ru.rgordeev.migrations: DEBUG

spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/migrations_snapshot
    username: migrations
    password: migrations
    name: app-dev-database
    driver-class-name: org.postgresql.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.hbm2ddl.auto: validate
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.query.plan_parameter_metadata_max_size: 2000
      hibernate.query.plan_cache_max_size: 20000
      hibernate.connection.provider_disables_autocommit: false
      hibernate.generate_statistics: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  liquibase:
    enabled: true
    contexts: fake,prod

server:
  port: 8080
